[2024-11-24T14:37:54.961+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-24T14:37:54.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: labour_force_survey_etl.send_email_notification manual__2024-11-24T14:37:47.875564+00:00 [queued]>
[2024-11-24T14:37:54.990+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: labour_force_survey_etl.send_email_notification manual__2024-11-24T14:37:47.875564+00:00 [queued]>
[2024-11-24T14:37:54.990+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-24T14:37:55.000+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_email_notification> on 2024-11-24 14:37:47.875564+00:00
[2024-11-24T14:37:55.008+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'labour_force_survey_etl', 'send_email_notification', 'manual__2024-11-24T14:37:47.875564+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/labour_force_survey_etl_dag.py', '--cfg-path', '/tmp/tmpb1_mpuj7']
[2024-11-24T14:37:55.011+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask send_email_notification
[2024-11-24T14:37:55.013+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-24T14:37:55.013+0000] {standard_task_runner.py:64} INFO - Started process 107 to run task
[2024-11-24T14:37:55.047+0000] {task_command.py:426} INFO - Running <TaskInstance: labour_force_survey_etl.send_email_notification manual__2024-11-24T14:37:47.875564+00:00 [running]> on host c92a3b38a917
[2024-11-24T14:37:55.195+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='njabuldinho@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='labour_force_survey_etl' AIRFLOW_CTX_TASK_ID='send_email_notification' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T14:37:47.875564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T14:37:47.875564+00:00'
[2024-11-24T14:37:55.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-24T14:37:55.219+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-11-24T14:37:55.219+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-11-24T14:37:55.219+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-11-24T14:37:55.220+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-24T14:37:55.220+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-11-24T14:37:55.227+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=labour_force_survey_etl, task_id=send_email_notification, run_id=manual__2024-11-24T14:37:47.875564+00:00, execution_date=20241124T143747, start_date=20241124T143754, end_date=20241124T143755
[2024-11-24T14:37:55.235+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task send_email_notification ([Errno 111] Connection refused; 107)
[2024-11-24T14:37:55.268+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-24T14:37:55.281+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T14:37:55.282+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
