[2024-11-24T15:12:39.345+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-24T15:12:39.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: labour_force_survey_etl.extract manual__2024-11-24T15:07:31.154211+00:00 [queued]>
[2024-11-24T15:12:39.377+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: labour_force_survey_etl.extract manual__2024-11-24T15:07:31.154211+00:00 [queued]>
[2024-11-24T15:12:39.378+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-24T15:12:39.389+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2024-11-24 15:07:31.154211+00:00
[2024-11-24T15:12:39.397+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'labour_force_survey_etl', 'extract', 'manual__2024-11-24T15:07:31.154211+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/labour_force_survey_etl_dag.py', '--cfg-path', '/tmp/tmpqnlhj4ke']
[2024-11-24T15:12:39.400+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask extract
[2024-11-24T15:12:39.401+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-24T15:12:39.402+0000] {standard_task_runner.py:64} INFO - Started process 207 to run task
[2024-11-24T15:12:39.440+0000] {task_command.py:426} INFO - Running <TaskInstance: labour_force_survey_etl.extract manual__2024-11-24T15:07:31.154211+00:00 [running]> on host 711bcacde839
[2024-11-24T15:12:39.511+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='labour_force_survey_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T15:07:31.154211+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T15:07:31.154211+00:00'
[2024-11-24T15:12:39.512+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-24T15:12:39.524+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-24T15:12:39.524+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/labour_force_survey_etl_dag.py", line 35, in extract
    df, meta = pyreadstat.read_sav(sav_file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyreadstat/pyreadstat.pyx", line 389, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat/_readstat_parser.pyx", line 1104, in pyreadstat._readstat_parser.run_conversion
pyreadstat._readstat_parser.PyreadstatError: File /opt/***/dags/LabourForceSurvey_dummy.sav does not exist!
[2024-11-24T15:12:39.531+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=labour_force_survey_etl, task_id=extract, run_id=manual__2024-11-24T15:07:31.154211+00:00, execution_date=20241124T150731, start_date=20241124T151239, end_date=20241124T151239
[2024-11-24T15:12:39.539+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task extract (File /opt/***/dags/LabourForceSurvey_dummy.sav does not exist!; 207)
[2024-11-24T15:12:39.578+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-24T15:12:39.595+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T15:12:39.598+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
